### ISSUE TITLE
Not Doing Anything After Putting Token In?

### ISSUE THREAD

**Issue by Stodius** [Sheepy1337/Epic-360-Discord-Nitro-Sniper#5]
Not sure if I'm doing anything wrong, it asks for my token, I put it in, and then it just stays like this - 
![Capture](https://user-images.githubusercontent.com/57733867/93667011-a8877a00-fa50-11ea-9349-8350f53810fa.PNG)

**Comment by Sheepy1337** [comment]
It means its working, and waiting for a nitro code to snipe
